apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init
  namespace: ratelimiter
data:
  001_init.sql: |
    CREATE TABLE IF NOT EXISTS endpoints (
        path VARCHAR(255) PRIMARY KEY,
        refill_wait_time_ms INTEGER NOT NULL,
        max_limit INTEGER NOT NULL,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: ratelimiter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:alpine
          env:
            - name: POSTGRES_USER
              value: admin
            - name: POSTGRES_PASSWORD
              value: secret
            - name: POSTGRES_DB
              value: gateway
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: init-sql
              mountPath: /docker-entrypoint-initdb.d
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "admin", "-d", "gateway"]
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: init-sql
          configMap:
            name: postgres-init
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: ratelimiter
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
